theme: jekyll-theme-cayman
title: YADOB
description: Yet Another Discord Open Bot
show_downloads: true
github:
  zip_url: >-
    https://github.com/jakobbouchard/yadob/releases/latest/download/yadob-v1.0.0.zip
google_analytics: UA-156012637-5
